### ISSUE TITLE
Font inconsistency

### ISSUE THREAD

**Issue by rodrigoalcarazdelaosa** [snitramodranoel/lecture#1]
Hi,
first of all thank you very much for this work. I've been using Metropolis Theme for my presentations and Tufte LaTeX for my handouts, but hadn't tried this approach (combining both in a single document, which is great).

I have noticed what I understand is an inconsistency with fonts. When I want to highlight text in Tufte LaTeX I usually use \textsc{} so that the text is written in small caps. However, for presentations, bold type is usually more convenient. With the current setup bold type uses Fira Sans Book whereas in the rest of the presentation Adobe Garamond Pro is used. You'll notice that if you try to put text in bold you get a mix of fonts in your presentation, which is not what I expected.

Also, Adobe Garamond Pro is not free isn't it?

Thanks a lot for this contribution!

**Comment by rodrigoalcarazdelaosa** [comment]
Related to this, is there any advantage of using Adobe Garamond Pro vs [EBGaramond](https://ctan.org/pkg/ebgaramond-maths)?

**Comment by snitramodranoel** [comment]
@alcarazr Thanks for using `lecture` and pointing out the issue with the fonts. I have changed the default font configuration to fix the bold inconsistency and remove any reference to the non-free font.
